apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my.app.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: appapi-service
            port:
              number: 80
      - path: /info
        pathType: Prefix
        backend:
          service:
            name: appinfo-service
            port:
              number: 80
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: applogin-service
            port:
              number: 80