apiVersion: v1
kind: Service
metadata:
  name: appapi-service
spec:
  selector:
    app: appapi
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appinfo-service
spec:
  selector:
    app: appinfo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: applogin-service
spec:
  selector:
    app: applogin
  ports:
  - port: 80
    targetPort: 80